import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import InitialLoadingIndicator from "./_components/global/InitialLoadingIndicator";
import Providers from "./_components/providers/Providers";

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased w-full`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
